@echo off
echo Setting environment
SET DAA_INPUTS_ROOT=%DAA_CORE_ROOT%\data
SET JSBSIM_ROOT=%DAA_CORE_ROOT%\data
SET TRASIM_DEV_ROOT=%DAA_CORE_ROOT%\daa_core
SET DAA_LOGIC_DEV_ROOT=%DAA_CORE_ROOT%\daa_core
SET QT_QPA_PLATFORM_PLUGIN_PATH=%DAA_SIMULATION_ROOT%\qt-5.9\bin\plugins

SET OPENDDS_BIN=%DAA_SIMULATION_ROOT%\opendds-3.11\bin
SET OPENSOA_BIN=%DAA_SIMULATION_ROOT%\opensoa-4.2.1\bin
SET BOOST_BIN=%DAA_SIMULATION_ROOT%\boost-1.64\bin
SET QT_BIN=%DAA_SIMULATION_ROOT%\qt-5.9\bin
SET POCO_BIN=%DAA_SIMULATION_ROOT%\poco-1.9.0\bin
SET OSG_BIN=%DAA_SIMULATION_ROOT%\osg-3.4.1\bin
SET OSGEARTH_BIN=%DAA_SIMULATION_ROOT%\osgearth-4.4.9\bin
SET GEOMAT_BIN=%DAA_SIMULATION_ROOT%\geomat_utils\bin
SET DEV_UTILS_BIN=%DAA_SIMULATION_ROOT%\dev_utils\bin

SET PATH=%PATH%;%DAA_CORE_ROOT%\bin;
SET PATH=%PATH%;%OPENDDS_BIN%;%OPENSOA_BIN%;%BOOST_BIN%;%QT_BIN%;%POCO_BIN%;%OSG_BIN%;%OSGEARTH_BIN%;%GEOMAT_BIN%;%DEV_UTILS_BIN%;